package com.chen.discipline.love.day.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chen.discipline.love.day.greendao.PersonLoveDay;
import com.chen.discipline.love.day.greendao.PersonMessage;

import com.chen.discipline.love.day.greendao.PersonLoveDayDao;
import com.chen.discipline.love.day.greendao.PersonMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personLoveDayDaoConfig;
    private final DaoConfig personMessageDaoConfig;

    private final PersonLoveDayDao personLoveDayDao;
    private final PersonMessageDao personMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personLoveDayDaoConfig = daoConfigMap.get(PersonLoveDayDao.class).clone();
        personLoveDayDaoConfig.initIdentityScope(type);

        personMessageDaoConfig = daoConfigMap.get(PersonMessageDao.class).clone();
        personMessageDaoConfig.initIdentityScope(type);

        personLoveDayDao = new PersonLoveDayDao(personLoveDayDaoConfig, this);
        personMessageDao = new PersonMessageDao(personMessageDaoConfig, this);

        registerDao(PersonLoveDay.class, personLoveDayDao);
        registerDao(PersonMessage.class, personMessageDao);
    }
    
    public void clear() {
        personLoveDayDaoConfig.clearIdentityScope();
        personMessageDaoConfig.clearIdentityScope();
    }

    public PersonLoveDayDao getPersonLoveDayDao() {
        return personLoveDayDao;
    }

    public PersonMessageDao getPersonMessageDao() {
        return personMessageDao;
    }

}
